/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthAccountRouteImport } from './routes/_auth/account'
import { Route as PublicExamplesClientOrpcRouteImport } from './routes/_public/examples/client-orpc'
import { Route as AuthExamplesClientOrpcAuthRouteImport } from './routes/_auth/examples/client-orpc-auth'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRoute,
} as any)
const PublicExamplesClientOrpcRoute =
  PublicExamplesClientOrpcRouteImport.update({
    id: '/examples/client-orpc',
    path: '/examples/client-orpc',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthExamplesClientOrpcAuthRoute =
  AuthExamplesClientOrpcAuthRouteImport.update({
    id: '/examples/client-orpc-auth',
    path: '/examples/client-orpc-auth',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/account': typeof AuthAccountRoute
  '/dashboard': typeof AuthDashboardRoute
  '/login': typeof PublicLoginRoute
  '/examples/client-orpc-auth': typeof AuthExamplesClientOrpcAuthRoute
  '/examples/client-orpc': typeof PublicExamplesClientOrpcRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/account': typeof AuthAccountRoute
  '/dashboard': typeof AuthDashboardRoute
  '/login': typeof PublicLoginRoute
  '/examples/client-orpc-auth': typeof AuthExamplesClientOrpcAuthRoute
  '/examples/client-orpc': typeof PublicExamplesClientOrpcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/account': typeof AuthAccountRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/examples/client-orpc-auth': typeof AuthExamplesClientOrpcAuthRoute
  '/_public/examples/client-orpc': typeof PublicExamplesClientOrpcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/login'
    | '/examples/client-orpc-auth'
    | '/examples/client-orpc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/login'
    | '/examples/client-orpc-auth'
    | '/examples/client-orpc'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/account'
    | '/_auth/dashboard'
    | '/_public/login'
    | '/_public/'
    | '/_auth/examples/client-orpc-auth'
    | '/_public/examples/client-orpc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/examples/client-orpc': {
      id: '/_public/examples/client-orpc'
      path: '/examples/client-orpc'
      fullPath: '/examples/client-orpc'
      preLoaderRoute: typeof PublicExamplesClientOrpcRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/examples/client-orpc-auth': {
      id: '/_auth/examples/client-orpc-auth'
      path: '/examples/client-orpc-auth'
      fullPath: '/examples/client-orpc-auth'
      preLoaderRoute: typeof AuthExamplesClientOrpcAuthRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountRoute: typeof AuthAccountRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthExamplesClientOrpcAuthRoute: typeof AuthExamplesClientOrpcAuthRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountRoute: AuthAccountRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthExamplesClientOrpcAuthRoute: AuthExamplesClientOrpcAuthRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicExamplesClientOrpcRoute: typeof PublicExamplesClientOrpcRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicExamplesClientOrpcRoute: PublicExamplesClientOrpcRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
