packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@prisma/client": true
  better-sqlite3: true
  electron: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: true
  msw: true
  unrs-resolver: true
