/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PublicRouteImport } from "./routes/_public";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as PublicIndexRouteImport } from "./routes/_public/index";
import { Route as PublicSignupRouteImport } from "./routes/_public/signup";
import { Route as PublicLoginRouteImport } from "./routes/_public/login";
import { Route as AuthDashboardRouteImport } from "./routes/_auth/dashboard";
import { Route as AuthAccountRouteImport } from "./routes/_auth/account";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc.$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as PublicExamplesSsrOrpcRouteImport } from "./routes/_public/examples/ssr-orpc";
import { Route as PublicExamplesIsrRouteImport } from "./routes/_public/examples/isr";
import { Route as PublicExamplesClientOrpcRouteImport } from "./routes/_public/examples/client-orpc";
import { Route as AuthExamplesSsrOrpcAuthRouteImport } from "./routes/_auth/examples/ssr-orpc-auth";
import { Route as AuthExamplesClientOrpcAuthRouteImport } from "./routes/_auth/examples/client-orpc-auth";

const PublicRoute = PublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PublicRoute,
} as any);
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => PublicRoute,
} as any);
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => PublicRoute,
} as any);
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthRoute,
} as any);
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => AuthRoute,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const PublicExamplesSsrOrpcRoute = PublicExamplesSsrOrpcRouteImport.update({
  id: "/examples/ssr-orpc",
  path: "/examples/ssr-orpc",
  getParentRoute: () => PublicRoute,
} as any);
const PublicExamplesIsrRoute = PublicExamplesIsrRouteImport.update({
  id: "/examples/isr",
  path: "/examples/isr",
  getParentRoute: () => PublicRoute,
} as any);
const PublicExamplesClientOrpcRoute = PublicExamplesClientOrpcRouteImport.update({
  id: "/examples/client-orpc",
  path: "/examples/client-orpc",
  getParentRoute: () => PublicRoute,
} as any);
const AuthExamplesSsrOrpcAuthRoute = AuthExamplesSsrOrpcAuthRouteImport.update({
  id: "/examples/ssr-orpc-auth",
  path: "/examples/ssr-orpc-auth",
  getParentRoute: () => AuthRoute,
} as any);
const AuthExamplesClientOrpcAuthRoute = AuthExamplesClientOrpcAuthRouteImport.update({
  id: "/examples/client-orpc-auth",
  path: "/examples/client-orpc-auth",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof PublicIndexRoute;
  "/account": typeof AuthAccountRoute;
  "/dashboard": typeof AuthDashboardRoute;
  "/login": typeof PublicLoginRoute;
  "/signup": typeof PublicSignupRoute;
  "/examples/client-orpc-auth": typeof AuthExamplesClientOrpcAuthRoute;
  "/examples/ssr-orpc-auth": typeof AuthExamplesSsrOrpcAuthRoute;
  "/examples/client-orpc": typeof PublicExamplesClientOrpcRoute;
  "/examples/isr": typeof PublicExamplesIsrRoute;
  "/examples/ssr-orpc": typeof PublicExamplesSsrOrpcRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof PublicIndexRoute;
  "/account": typeof AuthAccountRoute;
  "/dashboard": typeof AuthDashboardRoute;
  "/login": typeof PublicLoginRoute;
  "/signup": typeof PublicSignupRoute;
  "/examples/client-orpc-auth": typeof AuthExamplesClientOrpcAuthRoute;
  "/examples/ssr-orpc-auth": typeof AuthExamplesSsrOrpcAuthRoute;
  "/examples/client-orpc": typeof PublicExamplesClientOrpcRoute;
  "/examples/isr": typeof PublicExamplesIsrRoute;
  "/examples/ssr-orpc": typeof PublicExamplesSsrOrpcRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/_public": typeof PublicRouteWithChildren;
  "/_auth/account": typeof AuthAccountRoute;
  "/_auth/dashboard": typeof AuthDashboardRoute;
  "/_public/login": typeof PublicLoginRoute;
  "/_public/signup": typeof PublicSignupRoute;
  "/_public/": typeof PublicIndexRoute;
  "/_auth/examples/client-orpc-auth": typeof AuthExamplesClientOrpcAuthRoute;
  "/_auth/examples/ssr-orpc-auth": typeof AuthExamplesSsrOrpcAuthRoute;
  "/_public/examples/client-orpc": typeof PublicExamplesClientOrpcRoute;
  "/_public/examples/isr": typeof PublicExamplesIsrRoute;
  "/_public/examples/ssr-orpc": typeof PublicExamplesSsrOrpcRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/account"
    | "/dashboard"
    | "/login"
    | "/signup"
    | "/examples/client-orpc-auth"
    | "/examples/ssr-orpc-auth"
    | "/examples/client-orpc"
    | "/examples/isr"
    | "/examples/ssr-orpc"
    | "/api/auth/$"
    | "/api/rpc/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/account"
    | "/dashboard"
    | "/login"
    | "/signup"
    | "/examples/client-orpc-auth"
    | "/examples/ssr-orpc-auth"
    | "/examples/client-orpc"
    | "/examples/isr"
    | "/examples/ssr-orpc"
    | "/api/auth/$"
    | "/api/rpc/$";
  id:
    | "__root__"
    | "/_auth"
    | "/_public"
    | "/_auth/account"
    | "/_auth/dashboard"
    | "/_public/login"
    | "/_public/signup"
    | "/_public/"
    | "/_auth/examples/client-orpc-auth"
    | "/_auth/examples/ssr-orpc-auth"
    | "/_public/examples/client-orpc"
    | "/_public/examples/isr"
    | "/_public/examples/ssr-orpc"
    | "/api/auth/$"
    | "/api/rpc/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_public/": {
      id: "/_public/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof PublicIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/signup": {
      id: "/_public/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof PublicSignupRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/login": {
      id: "/_public/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof PublicLoginRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_auth/dashboard": {
      id: "/_auth/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthDashboardRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/account": {
      id: "/_auth/account";
      path: "/account";
      fullPath: "/account";
      preLoaderRoute: typeof AuthAccountRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_public/examples/ssr-orpc": {
      id: "/_public/examples/ssr-orpc";
      path: "/examples/ssr-orpc";
      fullPath: "/examples/ssr-orpc";
      preLoaderRoute: typeof PublicExamplesSsrOrpcRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/examples/isr": {
      id: "/_public/examples/isr";
      path: "/examples/isr";
      fullPath: "/examples/isr";
      preLoaderRoute: typeof PublicExamplesIsrRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/examples/client-orpc": {
      id: "/_public/examples/client-orpc";
      path: "/examples/client-orpc";
      fullPath: "/examples/client-orpc";
      preLoaderRoute: typeof PublicExamplesClientOrpcRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_auth/examples/ssr-orpc-auth": {
      id: "/_auth/examples/ssr-orpc-auth";
      path: "/examples/ssr-orpc-auth";
      fullPath: "/examples/ssr-orpc-auth";
      preLoaderRoute: typeof AuthExamplesSsrOrpcAuthRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/examples/client-orpc-auth": {
      id: "/_auth/examples/client-orpc-auth";
      path: "/examples/client-orpc-auth";
      fullPath: "/examples/client-orpc-auth";
      preLoaderRoute: typeof AuthExamplesClientOrpcAuthRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthAccountRoute: typeof AuthAccountRoute;
  AuthDashboardRoute: typeof AuthDashboardRoute;
  AuthExamplesClientOrpcAuthRoute: typeof AuthExamplesClientOrpcAuthRoute;
  AuthExamplesSsrOrpcAuthRoute: typeof AuthExamplesSsrOrpcAuthRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountRoute: AuthAccountRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthExamplesClientOrpcAuthRoute: AuthExamplesClientOrpcAuthRoute,
  AuthExamplesSsrOrpcAuthRoute: AuthExamplesSsrOrpcAuthRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute;
  PublicSignupRoute: typeof PublicSignupRoute;
  PublicIndexRoute: typeof PublicIndexRoute;
  PublicExamplesClientOrpcRoute: typeof PublicExamplesClientOrpcRoute;
  PublicExamplesIsrRoute: typeof PublicExamplesIsrRoute;
  PublicExamplesSsrOrpcRoute: typeof PublicExamplesSsrOrpcRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicExamplesClientOrpcRoute: PublicExamplesClientOrpcRoute,
  PublicExamplesIsrRoute: PublicExamplesIsrRoute,
  PublicExamplesSsrOrpcRoute: PublicExamplesSsrOrpcRoute,
};

const PublicRouteWithChildren = PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
