/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as ExamplesSsrOrpcAuthRouteImport } from './routes/examples/ssr-orpc-auth'
import { Route as ExamplesSsrOrpcRouteImport } from './routes/examples/ssr-orpc'
import { Route as ExamplesIsrRouteImport } from './routes/examples/isr'
import { Route as ExamplesClientOrpcAuthRouteImport } from './routes/examples/client-orpc-auth'
import { Route as ExamplesClientOrpcRouteImport } from './routes/examples/client-orpc'
import { Route as publicSignupRouteImport } from './routes/(public)/signup'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as authDashboardRouteImport } from './routes/(auth)/dashboard'
import { Route as authAccountRouteImport } from './routes/(auth)/account'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSsrOrpcAuthRoute = ExamplesSsrOrpcAuthRouteImport.update({
  id: '/examples/ssr-orpc-auth',
  path: '/examples/ssr-orpc-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSsrOrpcRoute = ExamplesSsrOrpcRouteImport.update({
  id: '/examples/ssr-orpc',
  path: '/examples/ssr-orpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIsrRoute = ExamplesIsrRouteImport.update({
  id: '/examples/isr',
  path: '/examples/isr',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesClientOrpcAuthRoute = ExamplesClientOrpcAuthRouteImport.update({
  id: '/examples/client-orpc-auth',
  path: '/examples/client-orpc-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesClientOrpcRoute = ExamplesClientOrpcRouteImport.update({
  id: '/examples/client-orpc',
  path: '/examples/client-orpc',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignupRoute = publicSignupRouteImport.update({
  id: '/(public)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authDashboardRoute = authDashboardRouteImport.update({
  id: '/(auth)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authAccountRoute = authAccountRouteImport.update({
  id: '/(auth)/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/account': typeof authAccountRoute
  '/dashboard': typeof authDashboardRoute
  '/login': typeof publicLoginRoute
  '/signup': typeof publicSignupRoute
  '/examples/client-orpc': typeof ExamplesClientOrpcRoute
  '/examples/client-orpc-auth': typeof ExamplesClientOrpcAuthRoute
  '/examples/isr': typeof ExamplesIsrRoute
  '/examples/ssr-orpc': typeof ExamplesSsrOrpcRoute
  '/examples/ssr-orpc-auth': typeof ExamplesSsrOrpcAuthRoute
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/account': typeof authAccountRoute
  '/dashboard': typeof authDashboardRoute
  '/login': typeof publicLoginRoute
  '/signup': typeof publicSignupRoute
  '/examples/client-orpc': typeof ExamplesClientOrpcRoute
  '/examples/client-orpc-auth': typeof ExamplesClientOrpcAuthRoute
  '/examples/isr': typeof ExamplesIsrRoute
  '/examples/ssr-orpc': typeof ExamplesSsrOrpcRoute
  '/examples/ssr-orpc-auth': typeof ExamplesSsrOrpcAuthRoute
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/account': typeof authAccountRoute
  '/(auth)/dashboard': typeof authDashboardRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/signup': typeof publicSignupRoute
  '/examples/client-orpc': typeof ExamplesClientOrpcRoute
  '/examples/client-orpc-auth': typeof ExamplesClientOrpcAuthRoute
  '/examples/isr': typeof ExamplesIsrRoute
  '/examples/ssr-orpc': typeof ExamplesSsrOrpcRoute
  '/examples/ssr-orpc-auth': typeof ExamplesSsrOrpcAuthRoute
  '/(public)/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/examples/client-orpc'
    | '/examples/client-orpc-auth'
    | '/examples/isr'
    | '/examples/ssr-orpc'
    | '/examples/ssr-orpc-auth'
    | '/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/examples/client-orpc'
    | '/examples/client-orpc-auth'
    | '/examples/isr'
    | '/examples/ssr-orpc'
    | '/examples/ssr-orpc-auth'
    | '/'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/(auth)/account'
    | '/(auth)/dashboard'
    | '/(public)/login'
    | '/(public)/signup'
    | '/examples/client-orpc'
    | '/examples/client-orpc-auth'
    | '/examples/isr'
    | '/examples/ssr-orpc'
    | '/examples/ssr-orpc-auth'
    | '/(public)/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAccountRoute: typeof authAccountRoute
  authDashboardRoute: typeof authDashboardRoute
  publicLoginRoute: typeof publicLoginRoute
  publicSignupRoute: typeof publicSignupRoute
  ExamplesClientOrpcRoute: typeof ExamplesClientOrpcRoute
  ExamplesClientOrpcAuthRoute: typeof ExamplesClientOrpcAuthRoute
  ExamplesIsrRoute: typeof ExamplesIsrRoute
  ExamplesSsrOrpcRoute: typeof ExamplesSsrOrpcRoute
  ExamplesSsrOrpcAuthRoute: typeof ExamplesSsrOrpcAuthRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/ssr-orpc-auth': {
      id: '/examples/ssr-orpc-auth'
      path: '/examples/ssr-orpc-auth'
      fullPath: '/examples/ssr-orpc-auth'
      preLoaderRoute: typeof ExamplesSsrOrpcAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/ssr-orpc': {
      id: '/examples/ssr-orpc'
      path: '/examples/ssr-orpc'
      fullPath: '/examples/ssr-orpc'
      preLoaderRoute: typeof ExamplesSsrOrpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/isr': {
      id: '/examples/isr'
      path: '/examples/isr'
      fullPath: '/examples/isr'
      preLoaderRoute: typeof ExamplesIsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/client-orpc-auth': {
      id: '/examples/client-orpc-auth'
      path: '/examples/client-orpc-auth'
      fullPath: '/examples/client-orpc-auth'
      preLoaderRoute: typeof ExamplesClientOrpcAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/client-orpc': {
      id: '/examples/client-orpc'
      path: '/examples/client-orpc'
      fullPath: '/examples/client-orpc'
      preLoaderRoute: typeof ExamplesClientOrpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/signup': {
      id: '/(public)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/dashboard': {
      id: '/(auth)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/account': {
      id: '/(auth)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof authAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authAccountRoute: authAccountRoute,
  authDashboardRoute: authDashboardRoute,
  publicLoginRoute: publicLoginRoute,
  publicSignupRoute: publicSignupRoute,
  ExamplesClientOrpcRoute: ExamplesClientOrpcRoute,
  ExamplesClientOrpcAuthRoute: ExamplesClientOrpcAuthRoute,
  ExamplesIsrRoute: ExamplesIsrRoute,
  ExamplesSsrOrpcRoute: ExamplesSsrOrpcRoute,
  ExamplesSsrOrpcAuthRoute: ExamplesSsrOrpcAuthRoute,
  publicIndexRoute: publicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
