/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesSsrOrpcAuthRouteImport } from './routes/examples/ssr-orpc-auth'
import { Route as ExamplesSsrOrpcRouteImport } from './routes/examples/ssr-orpc'
import { Route as ExamplesIsrRouteImport } from './routes/examples/isr'
import { Route as ExamplesClientOrpcAuthRouteImport } from './routes/examples/client-orpc-auth'
import { Route as ExamplesClientOrpcRouteImport } from './routes/examples/client-orpc'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSsrOrpcAuthRoute = ExamplesSsrOrpcAuthRouteImport.update({
  id: '/examples/ssr-orpc-auth',
  path: '/examples/ssr-orpc-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSsrOrpcRoute = ExamplesSsrOrpcRouteImport.update({
  id: '/examples/ssr-orpc',
  path: '/examples/ssr-orpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIsrRoute = ExamplesIsrRouteImport.update({
  id: '/examples/isr',
  path: '/examples/isr',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesClientOrpcAuthRoute = ExamplesClientOrpcAuthRouteImport.update({
  id: '/examples/client-orpc-auth',
  path: '/examples/client-orpc-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesClientOrpcRoute = ExamplesClientOrpcRouteImport.update({
  id: '/examples/client-orpc',
  path: '/examples/client-orpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/examples/client-orpc': typeof ExamplesClientOrpcRoute
  '/examples/client-orpc-auth': typeof ExamplesClientOrpcAuthRoute
  '/examples/isr': typeof ExamplesIsrRoute
  '/examples/ssr-orpc': typeof ExamplesSsrOrpcRoute
  '/examples/ssr-orpc-auth': typeof ExamplesSsrOrpcAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/examples/client-orpc': typeof ExamplesClientOrpcRoute
  '/examples/client-orpc-auth': typeof ExamplesClientOrpcAuthRoute
  '/examples/isr': typeof ExamplesIsrRoute
  '/examples/ssr-orpc': typeof ExamplesSsrOrpcRoute
  '/examples/ssr-orpc-auth': typeof ExamplesSsrOrpcAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/examples/client-orpc': typeof ExamplesClientOrpcRoute
  '/examples/client-orpc-auth': typeof ExamplesClientOrpcAuthRoute
  '/examples/isr': typeof ExamplesIsrRoute
  '/examples/ssr-orpc': typeof ExamplesSsrOrpcRoute
  '/examples/ssr-orpc-auth': typeof ExamplesSsrOrpcAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/examples/client-orpc'
    | '/examples/client-orpc-auth'
    | '/examples/isr'
    | '/examples/ssr-orpc'
    | '/examples/ssr-orpc-auth'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/examples/client-orpc'
    | '/examples/client-orpc-auth'
    | '/examples/isr'
    | '/examples/ssr-orpc'
    | '/examples/ssr-orpc-auth'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/examples/client-orpc'
    | '/examples/client-orpc-auth'
    | '/examples/isr'
    | '/examples/ssr-orpc'
    | '/examples/ssr-orpc-auth'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ExamplesClientOrpcRoute: typeof ExamplesClientOrpcRoute
  ExamplesClientOrpcAuthRoute: typeof ExamplesClientOrpcAuthRoute
  ExamplesIsrRoute: typeof ExamplesIsrRoute
  ExamplesSsrOrpcRoute: typeof ExamplesSsrOrpcRoute
  ExamplesSsrOrpcAuthRoute: typeof ExamplesSsrOrpcAuthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/ssr-orpc-auth': {
      id: '/examples/ssr-orpc-auth'
      path: '/examples/ssr-orpc-auth'
      fullPath: '/examples/ssr-orpc-auth'
      preLoaderRoute: typeof ExamplesSsrOrpcAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/ssr-orpc': {
      id: '/examples/ssr-orpc'
      path: '/examples/ssr-orpc'
      fullPath: '/examples/ssr-orpc'
      preLoaderRoute: typeof ExamplesSsrOrpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/isr': {
      id: '/examples/isr'
      path: '/examples/isr'
      fullPath: '/examples/isr'
      preLoaderRoute: typeof ExamplesIsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/client-orpc-auth': {
      id: '/examples/client-orpc-auth'
      path: '/examples/client-orpc-auth'
      fullPath: '/examples/client-orpc-auth'
      preLoaderRoute: typeof ExamplesClientOrpcAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/client-orpc': {
      id: '/examples/client-orpc'
      path: '/examples/client-orpc'
      fullPath: '/examples/client-orpc'
      preLoaderRoute: typeof ExamplesClientOrpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ExamplesClientOrpcRoute: ExamplesClientOrpcRoute,
  ExamplesClientOrpcAuthRoute: ExamplesClientOrpcAuthRoute,
  ExamplesIsrRoute: ExamplesIsrRoute,
  ExamplesSsrOrpcRoute: ExamplesSsrOrpcRoute,
  ExamplesSsrOrpcAuthRoute: ExamplesSsrOrpcAuthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
